class TerminateException(Exception):
    pass

class ResetCoreException(Exception):
    pass